### PR TITLE
Nginx migration

### PR DESCRIPTION
**Pull request by tomaszmrugalski**
To get python 3.9, I upgraded the server to Debian 11. Sadly, the apache configuration broke down with a very weird infinite loop appearing when importing scipy under wsgi module in apache. After couple days of no progress at all, I decided to try an alternative.

As a result, we're running on Nginx and all seem to be working fine. I've decided it's a good opportunity to document this. Hence the Nginx and some Apache configuration tweaks.

### CODE REVIEW

**Comment by tomaszmrugalski** [comment]
I don't care about quality of this that much. What's the chance anyone would set up a server instance of this?

**Comment by fivitti** [comment]
I'm not an Nginx/apache expert, but it looks fine for me.
I think that is a big chance that we will use this configuration. ;)

**Review by fivitti — APPROVED** [review]
I'm not an Nginx/apache expert, but it looks fine for me.
I think that is a big chance that we will use this configuration. ;)

**Comment by tomaszmrugalski** [comment]
> I think that is a big chance that we will use this configuration. ;)

We already do. The reason I did this is I couldn't make it work on Python 3.9 on Debian 11 with Apache. The scipy import kept getting stuck in infinite loop with some futex. This didn't happen when I was importing into python interpreter or when running Flask from command line.

Thanks for the review!

**Pull request merged**
