### PR TITLE
74 gallery improvements

### LINKED ISSUE #74: UI: gallery improvements (broken for portait photos, no ESC, no next/prev photo)
After #71 was merged, I've uploaded a [bunch of new photos](https://svarog.space/station/1). It seems that the gallery works OK, if the photo is in landscape orientation. However, the portrait photos are too large and don't fit on the screen. This brings three problems:

- [ ] photos should be scaled so they fit on the screen
- [ ] pressing ESC should close the overlay photo
- [ ] pressing left, right arrow should move to the next/prev photo
- [ ] there should be small arrows to move to the next/prev photo

Oh well. Another day, broken thing.

### PR DESCRIPTION
**Pull request by fivitti**
Resolves #74.

Replace the gallery with [ViewerJS](https://github.com/fengyuanchen/viewerjs).

### CODE REVIEW

**Comment by fivitti** [comment]
- [x] photos should be scaled so they fit on the screen
- [x] pressing ESC should close the overlay photo
- [x] pressing left, right arrow should move to the next/prev photo
- [x] there should be small arrows to move to the next/prev photo

**Comment by fivitti** [comment]
Screenshot from 2022-02-19 21-22-48

Screenshot from 2022-02-19 21-23-01

**Comment by tomaszmrugalski** [comment]
I've tested it and it looks great! Thanks a lot.

Ready for merge!

**Review by tomaszmrugalski — APPROVED** [review]
Unit-tests pass, works on my local system. And looks great!

**Pull request merged**
