### PR TITLE
Web station gallery

### PR DESCRIPTION
**Pull request by tomaszmrugalski**
The goal of this ticket is to improve the situation with the image gallery shown for stations. There's couple reasons for this work. First, there's an old ticket #22 calling to have the ability to add and manage more stations. This is a step towards being able to describe the station better, with images with descriptions. Second, the TKiS-1 station evolved and I'd like to describe the changes. Being able to upload images with description will be useful for that. Third, there's SKORCZ-1 station that's being active, but lack images. Finally, the previous "gallery" was a primitive hack done on tables.

This is a work in progress and is not ready for review yet.

### CODE REVIEW

**Comment by tomaszmrugalski** [comment]
hey @fivitti, what are your thoughts on station management? The need here is to do some basic edits (edit description and configuration of the station, do some basic management of the image gallery). I can see this being done in one of two ways.

Option 1: if you're logged as station admin, you see edit buttons next to each field. You click it, then edit this one field and you're done. You never leave this `/station/{id}` page. This approach has more modern approach, but is probably more tricky to implement.
Option 2: If you're logged as station admin, you can navigate to `/station/{id}/edit` and there's a form with the fields being editable. Once you save the changes, you can navigate to `/station/{id}` to actually see the changes. This is probably more secure as you can better control who can access the page.

Any thoughts on this?

**Comment by fivitti** [comment]
Option 1 and 2 are almost the same.
It seems that option 1 requires using Javascript to activate the edit form.
I think option 2. will be more straightforward and consistent with other `Svarog` parts.

**Comment by tomaszmrugalski** [comment]
Ok, it's ready for review. I'm too lazy to write unit-tests for this. Now what? ;)

**Comment by tomaszmrugalski** [comment]
Fivitti is busy with other things. This is not a complex change, so I've decided to go ahead and merge it.

**Pull request merged**
